### ISSUE TITLE
Please add a "source code" link to your rubygems page

### ISSUE THREAD

**Issue by jaredbeck** [a2ikm/capistrano-pending#6]
I couldn't find a link from [your rubygems page][1] to your github repo. You can add one by logging into rubygems and editing the profile for your gem.

Thanks!

[1]: https://rubygems.org/gems/capistrano-pending

**Comment by a2ikm** [comment]
I added "source code" link, thanks!

**Comment by jaredbeck** [comment]
Thanks!
